### ISSUE TITLE
Can Startup Scripts Halt The Startup Of The Image?

### ISSUE THREAD

**Issue by hoshposh** [caf-archive/opensuse-base-image#13]
With the `/startup` approach where derived images can drop-in scripts that should be executed prior to an images `CMD` instruction being invoked, is there a way for the drop-in startup scripts to stop the image from starting?

I am looking for an invocation pattern example, where I can add checks in my startup scripts to indicate that an image should not start for things like:

* A database connection is not available after some short timeout period.
* The underlying database schema is not at the correct level.
* Required environment variables have not been set.

In my current `entrypoint.sh` script I perform these types of checks and stop the image with an error, but as I migrate to using the CAF startup facility I am looking for the correct approach to use.

**Comment by dermot-hardy** [comment]
It's like you're reading my mind.

https://portal.digitalsafe.net/browse/SCMOD-7700 covers this and I just moved it into the next sprint this morning.

![image](https://user-images.githubusercontent.com/20627297/83432023-2129e280-a430-11ea-99c1-fe430ec05973.png)
