### ISSUE TITLE
The JDK is not fully AWT compliant

### ISSUE THREAD

**Issue by steve-williams-mf** [caf-archive/opensuse-base-image#16]
This JDK is not fully AWT compliant, which results in failures for applications.  

Our product utilize Jasper Reports to create pdf based reports

This jdk did not the necessary AWT packages that  in headless mode that allowed Japser Reports to initialize when trying to generate a pdf report.  

By default in a headless mode, the necessary AWT packages need to be installed in this jdk so that any potential graphics in the application or reports  to potentially render graphics into PDF files (pie charts, etc.)

Per an email from Dermont, we installed the dejavu-fonts which resolved the issue.

**Comment by dermot-hardy** [comment]
Hi,

These changes have been made but obviously the images aren't scheduled to be released again for another couple of months.  We can bring that forward if you want or you can pull them from the prereleases repository in the meantime.

    docker login dockerhub-private.svsartifactory.swinfra.net
    docker image pull dockerhub-private.svsartifactory.swinfra.net/cafinternal/prereleases:opensuse-base-2.2.0-SNAPSHOT
    docker image pull dockerhub-private.svsartifactory.swinfra.net/cafinternal/prereleases:opensuse-jre8-3.2.0-SNAPSHOT
    docker image pull dockerhub-private.svsartifactory.swinfra.net/cafinternal/prereleases:opensuse-jdk8-3.2.0-SNAPSHOT
    docker image pull dockerhub-private.svsartifactory.swinfra.net/cafinternal/prereleases:opensuse-tomcat-5.2.0-SNAPSHOT
    etc.

- The prereleases repository is internal-only and you'll need to login to it if you haven't already done so in the past.
- You can login with either SWINFRA domain or CORPDOM domain credentials.
  - To use SWINFRA credentials use your swinfra logon name as the username (i.e. `hardyde` for me)
  - To use CORPDOM credentials use the full corpdom user principal name as the username (i.e. `dermot.hardy@microfocus.com` for me)

Thanks,
Dermot
